In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv('data.csv')

In [3]:
dataset

country   age   salary purchased
0   France  44.0  72000.0        No
1    spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    spain  38.0  61000.0        No
4  Germany  40.0      NaN        No
5   France  35.0  58000.0       Yes
6    spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [6]:
x=dataset[['country','age','salary']].values

In [7]:
x

array([['France', 44.0, 72000.0],
       ['spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [12]:
y=dataset['purchased'].values

In [13]:
y

array(['No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [14]:
from sklearn.impute import SimpleImputer

In [15]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')

In [16]:
imputer=imputer.fit(x[:,1:3])

In [17]:
x[:,1:3]=imputer.transform(x[:,1:3])

In [18]:
x

array([['France', 44.0, 72000.0],
       ['spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
label_encoder_x=LabelEncoder()

In [21]:
x[:,0]=label_encoder_x.fit_transform(x[:,0])

In [22]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [23]:
from sklearn.preprocessing import OneHotEncoder

In [24]:
onehotencoder=OneHotEncoder()

In [26]:
x=onehotencoder.fit_transform(dataset.country.values.reshape(-1,1)).toarray()

In [27]:
x

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [28]:
labelencoder_y=LabelEncoder()

In [29]:
y=labelencoder_y.fit_transform(y)

In [30]:
y

array([0, 1, 0, 0, 0, 1, 0, 1, 0, 1])

In [32]:
from sklearn.model_selection import train_test_split

In [35]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [36]:
x_train

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [37]:
x_test

array([[0., 1., 0.],
       [0., 1., 0.]])

In [38]:
y_train

array([0, 1, 1, 0, 1, 0, 0, 1])

In [39]:
y_test

array([0, 0])

In [40]:
from sklearn.preprocessing import StandardScaler

In [41]:
sc_x=StandardScaler()

In [42]:
x_train=sc_x.fit_transform(x_train)

In [49]:
x_test=sc_x.transform(x_test)

In [50]:
x_train

array([[-1.        ,  2.64575131, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667]])

In [51]:
x_test

array([[ 1.        , -2.64575131,  0.77459667],
       [ 1.        , -2.64575131,  0.77459667]])